name: stryker-dashboard

trigger:
  batch: true
  branches:
    include:
    - refs/heads/master
    - refs/tags/*

resources:
- repo: self
  clean: true

pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: Install
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -unsafe-perm'

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    verbose: false
    customCommand: run all

- task: ArchiveFiles@2
  displayName: 'Archive Monitoring agent function'
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/packages/badge-api'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/badge-api.zip'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/badge-api.zip'
    artifact: 'badge-api'