name: stryker-dashboard

trigger:
  batch: true
  branches:
    include:
    - refs/heads/master
    - refs/tags/*

resources:
- repo: self
  clean: true

pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: Install
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -unsafe-perm'

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    verbose: false
    customCommand: all