# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your Github Repository by following README.md
# 2. Replace PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME with your Azure function app name
# 3. Add this yaml file to your project's .github/workflows/
# 4. Push your local project to your Github Repository

name: Deploy Azure Function APP

on:
  push:
    branches:
    - feat/azure-function-app-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v1
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Run npm'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for npm in pushd
        pushd .
        npm install
        npm run build --if-present
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: stryker-mutator-badge-api
        # If your function app project is not located in your repository's root
        # Please consider prefixing the project path in this package parameter
        package: 'packages/badge-api'
    #- name: 'use the published functionapp url in upcoming steps'
    #  run: |
    #    echo "${{ steps.fa.outputs.app-url }}"

# For more information on Github Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions